build_rag.sh: add libraries required by opencv-python
Fixes the following error when importing "cv2":

  ImportError: libGL.so.1: cannot open shared object file: No such file or directory

Signed-off-by: Mike Bonnet <mikeb@redhat.com>