Improve error message when modelscope is needed and missing
Before:

    Error:
    Optional: ModelScope models require the modelscope module.
    This module can be installed via PyPI tools like uv, pip, pip3, pipx, or via
    distribution package managers like dnf or apt. Example:
    uv pip install modelscope

After:

    Error: This operation requires modelscope which is not available.

    This tool can be installed via PyPI tools like uv, pip, pip3 or pipx. Example:

    pip install modelscope

In particular:

    - follows the same structure of error message as in `huggingface` module

    - separate error from the explanation and guidance by new line

    - explain that this particular operation requires the CLI tool -
      currently the error is displayed on login, logout or push. Implies
      that some other operations might not require this tool

    - provide `pip` as first example how to solve the issue (that's also
      the tool mention in the README)

    - there aren't any distribution deb nor rpm packages with modelscope
      so remove that guidance

    - `modelscope` is a command line tool, not a module as it was
      referred before

Fixes: #1766

Signed-off-by: Pavol Babincak <pbabinca@redhat.com>