Improve error message when huggingface-cli is needed and missing
Before:

    Error:
    Optional: Huggingface models require the huggingface-cli module.
    This module can be installed via PyPI tools like uv, pip, pip3, pipx, or via
    distribution package managers like dnf or apt. Example:
    uv pip install huggingface_hub

After:

    Error: Huggingface models require the huggingface-cli tool.

    This tool can be installed via PyPI tools like uv, pip, pip3, pipx. Example:

    pip install -U "huggingface_hub[cli]"

    Or via distribution package managers like dnf or apt. Example:

    sudo dnf install python3-huggingface-hub

In particular:

    - separate error from the explanation and guidance by new line,

    - provide `pip` as first example how to solve the issue (that's also the
    tool mention in the README)

    - use same package extra as official documentation to install the CLI
    tool: https://huggingface.co/docs/huggingface_hub/en/guides/cli

    - provide example with dnf command to install the package (dnf is also
    mentioned in the README file)

    - `huggingface-cli` is a command line tool, not a module as it was
    referred before

Fixes: #1766

Signed-off-by: Pavol Babincak <pbabinca@redhat.com>