tests: generate tmpdir store for ollama pull testcase
Two reasons to do so:

1. The directory is cleaned up on test completed;

2. The hardcoded directory may not be available for write to the current
   process (because some other process is running the test suite in
   parallel, or because someone chmod -rwx the directory for some
   reason).

In which case the test case fails with:
PermissionError: [Errno 13] Permission denied: '/tmp/ramalama/store'

This failure was triggered in nixpkgs CI:
https://hydra.nixos.org/build/305125672

Signed-off-by: Ihar Hrachyshka <ihar.hrachyshka@gmail.com>