Support huggingface-cli older than 0.25.0, like on Fedora 40 and 41
Currently, on Fedora 40 and 41, pulling a model from Hugging Face fails
with:
  $ ramalama pull
      huggingface://afrideva/Tiny-Vicuna-1B-GGUF/tiny-vicuna-1b.q2_k.gguf
  usage: huggingface-cli <command> [<args>]
  huggingface-cli: error: argument {env,login,whoami,logout,repo,upload,
      download,lfs-enable-largefiles,lfs-multipart-upload,scan-cache,
      delete-cache,tag}: invalid choice: 'version' (choose from 'env',
      'login', 'whoami', 'logout', 'repo', 'upload', 'download',
      'lfs-enable-largefiles', 'lfs-multipart-upload', 'scan-cache',
      'delete-cache', 'tag')
  Error: Command '['huggingface-cli', 'version']' returned non-zero exit
      status 2.

This is because the 'huggingface-cli version' command is a recent
addition in version 0.25.0 [1], and it's not present in any stable
Fedora release [2].

Therefore, it might be worth using a slightly different signature to
detect the presence of huggingface-cli - one that isn't bound to a
huggingface-cli version and is used elsewhere in the code.

[1] huggingface_hub commit ebac1b2a1aa4a9f4
    https://github.com/huggingface/huggingface_hub/commit/ebac1b2a1aa4a9f4
    https://github.com/huggingface/huggingface_hub/issues/2441

[2] https://src.fedoraproject.org/rpms/python-huggingface-hub

Fixes: 5749154b1e21b802 ("Replace huggingface-cli with a simple ...")

Signed-off-by: Debarshi Ray <rishi@fedoraproject.org>