Improve error message when huggingface-cli is needed and missing
Before:

    Error:
    Optional: Huggingface models require the huggingface-cli module.
    This module can be installed via PyPI tools like uv, pip, pip3, pipx, or via
    distribution package managers like dnf or apt. Example:
    uv pip install huggingface_hub

After:

    Error: This operation requires huggingface-cli which is not available.

    This tool can be installed via PyPI tools like uv, pip, pip3 or pipx. Example:

    pip install -U "huggingface_hub[cli]"

    Or via distribution package managers like dnf or apt. Example:

    sudo dnf install python3-huggingface-hub

In particular:

    - separate error from the explanation and guidance by new line

    - explain that this particular operation requires the CLI tool -
      currently the error is displayed on login, logout or push. Implies
      that some other operations might not require this tool

    - provide `pip` as first example how to solve the issue (that's also
      the tool mention in the README)

    - use same package extra as official documentation to install the
      CLI tool: https://huggingface.co/docs/huggingface_hub/en/guides/cli

    - provide example with dnf command to install the package (dnf is
      also mentioned in the README file)

    - `huggingface-cli` is a command line tool, not a module as it was
      referred before

Fixes: #1766

Signed-off-by: Pavol Babincak <pbabinca@redhat.com>